name: Execute Unit Tests

on: 
  workflow_dispatch:

jobs:
  execute-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Execute unit tests
        run: | 
          dotnet test --no-build --logger "trx;LogFileName=test_results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

      - name: Upload UnitTest results as an artifact
        uses: actions/upload-artifact@v3
        with: 
          name: test-results
          path: ./Calculator.Tests/TestResults/*.trx

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./Calculator.Tests/TestResults/*.trx
