name: Generate Test Results

on:
  pull_request:
    branches:
      - main

jobs:
  generate-test-results:
    runs-on: ubuntu-latest
    - name: Generate test results
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        echo "Generating test results..."
        echo "Test results for pull request" > test-results-$TIMESTAMP.txt
        echo "All tests passed!" >> test-results-$TIMESTAMP.txt

    - name: Push to GH Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan gh-pages
        git reset --hard
        mv test-results-*.txt index.html
        git add index.html
        git commit -m "Update test results"
        git push -f origin gh-pages
